name: Checks

on:
  push:
    branches: ["master"]
  pull_request:
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cargo build
        run: cargo build
      - name: Cargo test
        run: cargo test
      - name: Rustfmt
        run: cargo fmt --check
